# Generated by Django 2.2.7 on 2019-12-09 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
