# Generated by Django 2.2.7 on 2019-12-09 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_auto_20191209_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='budget.User'),
            preserve_default=False,
        ),
    ]
